# Generated by Django 5.2.7 on 2025-10-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('t_id', models.PositiveIntegerField()),
                ('image', models.ImageField(default='def.png', upload_to='teacher/image', verbose_name='')),
            ],
        ),
    ]
